name: make-test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test_and_build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: setup
        run: ./setup.sh
      - name: test
        run: make test
      - name: build
        run: make tcpServer